import { env } from '../env'

export const environment = {
    REACT_APP_API_KEY: env.REACT_APP_API_KEY,
    REACT_APP_AUTH_DOMAIN: env.REACT_APP_AUTH_DOMAIN,
    REACT_APP_PROJECT_ID: env.REACT_APP_PROJECT_ID,
    REACT_APP_MESSAGING_SENDER_ID: env.REACT_APP_MESSAGING_SENDER_ID,
    REACT_APP_STORAGE_BUCKET: env.REACT_APP_STORAGE_BUCKET,
    REACT_APP_APP_ID: env.REACT_APP_APP_ID
};
